controller_manager_msgs:
  ubuntu:
  - ros-humble-controller-manager-msgs
franka_bringup:
  ubuntu:
  - ros-humble-franka-bringup
franka_description:
  ubuntu:
  - ros-humble-franka-description
franka_moveit_config:
  ubuntu:
  - ros-humble-franka-moveit-config
franka_msgs:
  ubuntu:
  - ros-humble-franka-msgs
integration_launch_testing:
  ubuntu:
  - ros-humble-integration-launch-testing
joint_limits:
  ubuntu:
  - ros-humble-joint-limits
libfranka:
  ubuntu:
  - ros-humble-libfranka
franka_gripper:
  ubuntu:
  - ros-humble-franka-gripper
moveit:
  ubuntu:
  - ros-humble-moveit
moveit_common:
  ubuntu:
  - ros-humble-moveit-common
moveit_configs_utils:
  ubuntu:
  - ros-humble-moveit-configs-utils
moveit_msgs:
  ubuntu:
  - ros-humble-moveit-msgs
moveit_core:
  ubuntu:
  - ros-humble-moveit-core
chomp_motion_planner:
  ubuntu:
  - ros-humble-chomp-motion-planner
moveit_chomp_optimizer_adapter:
  ubuntu:
  - ros-humble-moveit-chomp-optimizer-adapter
moveit_planners:
  ubuntu:
  - ros-humble-moveit-planners
moveit_planners_chomp:
  ubuntu:
  - ros-humble-moveit-planners-chomp
moveit_planners_stomp:
  ubuntu:
  - ros-humble-moveit-planners-stomp
moveit_plugins:
  ubuntu:
  - ros-humble-moveit-plugins
moveit_resources_prbt_ikfast_manipulator_plugin:
  ubuntu:
  - ros-humble-moveit-resources-prbt-ikfast-manipulator-plugin
moveit_resources_prbt_moveit_config:
  ubuntu:
  - ros-humble-moveit-resources-prbt-moveit-config
moveit_resources_prbt_pg70_support:
  ubuntu:
  - ros-humble-moveit-resources-prbt-pg70-support
moveit_resources_prbt_support:
  ubuntu:
  - ros-humble-moveit-resources-prbt-support
moveit_ros:
  ubuntu:
  - ros-humble-moveit-ros
moveit_ros_occupancy_map_monitor:
  ubuntu:
  - ros-humble-moveit-ros-occupancy-map-monitor
moveit_ros_planning:
  ubuntu:
  - ros-humble-moveit-ros-planning
moveit_kinematics:
  ubuntu:
  - ros-humble-moveit-kinematics
moveit_planners_ompl:
  ubuntu:
  - ros-humble-moveit-planners-ompl
moveit_ros_move_group:
  ubuntu:
  - ros-humble-moveit-ros-move-group
moveit_ros_perception:
  ubuntu:
  - ros-humble-moveit-ros-perception
moveit_ros_robot_interaction:
  ubuntu:
  - ros-humble-moveit-ros-robot-interaction
moveit_ros_warehouse:
  ubuntu:
  - ros-humble-moveit-ros-warehouse
moveit_ros_benchmarks:
  ubuntu:
  - ros-humble-moveit-ros-benchmarks
moveit_runtime:
  ubuntu:
  - ros-humble-moveit-runtime
moveit_simple_controller_manager:
  ubuntu:
  - ros-humble-moveit-simple-controller-manager
moveit_ros_control_interface:
  ubuntu:
  - ros-humble-moveit-ros-control-interface
moveit_ros_planning_interface:
  ubuntu:
  - ros-humble-moveit-ros-planning-interface
moveit_hybrid_planning:
  ubuntu:
  - ros-humble-moveit-hybrid-planning
moveit_py:
  ubuntu:
  - ros-humble-moveit-py
moveit_ros_visualization:
  ubuntu:
  - ros-humble-moveit-ros-visualization
moveit_servo:
  ubuntu:
  - ros-humble-moveit-servo
moveit_setup_framework:
  ubuntu:
  - ros-humble-moveit-setup-framework
moveit_setup_app_plugins:
  ubuntu:
  - ros-humble-moveit-setup-app-plugins
moveit_setup_controllers:
  ubuntu:
  - ros-humble-moveit-setup-controllers
moveit_setup_core_plugins:
  ubuntu:
  - ros-humble-moveit-setup-core-plugins
moveit_setup_srdf_plugins:
  ubuntu:
  - ros-humble-moveit-setup-srdf-plugins
moveit_setup_assistant:
  ubuntu:
  - ros-humble-moveit-setup-assistant
pilz_industrial_motion_planner_testutils:
  ubuntu:
  - ros-humble-pilz-industrial-motion-planner-testutils
pilz_industrial_motion_planner:
  ubuntu:
  - ros-humble-pilz-industrial-motion-planner
robotiq_description:
  ubuntu:
  - ros-humble-robotiq-description
ros2_control:
  ubuntu:
  - ros-humble-ros2-control
ros2_control_test_assets:
  ubuntu:
  - ros-humble-ros2-control-test-assets
hardware_interface:
  ubuntu:
  - ros-humble-hardware-interface
controller_interface:
  ubuntu:
  - ros-humble-controller-interface
controller_manager:
  ubuntu:
  - ros-humble-controller-manager
diff_drive_controller:
  ubuntu:
  - ros-humble-diff-drive-controller
force_torque_sensor_broadcaster:
  ubuntu:
  - ros-humble-force-torque-sensor-broadcaster
forward_command_controller:
  ubuntu:
  - ros-humble-forward-command-controller
effort_controllers:
  ubuntu:
  - ros-humble-effort-controllers
franka_hardware:
  ubuntu:
  - ros-humble-franka-hardware
franka_semantic_components:
  ubuntu:
  - ros-humble-franka-semantic-components
franka_example_controllers:
  ubuntu:
  - ros-humble-franka-example-controllers
franka_robot_state_broadcaster:
  ubuntu:
  - ros-humble-franka-robot-state-broadcaster
gripper_controllers:
  ubuntu:
  - ros-humble-gripper-controllers
imu_sensor_broadcaster:
  ubuntu:
  - ros-humble-imu-sensor-broadcaster
joint_state_broadcaster:
  ubuntu:
  - ros-humble-joint-state-broadcaster
joint_trajectory_controller:
  ubuntu:
  - ros-humble-joint-trajectory-controller
admittance_controller:
  ubuntu:
  - ros-humble-admittance-controller
position_controllers:
  ubuntu:
  - ros-humble-position-controllers
robotiq_controllers:
  ubuntu:
  - ros-humble-robotiq-controllers
ros2_controllers:
  ubuntu:
  - ros-humble-ros2-controllers
ros2_controllers_test_nodes:
  ubuntu:
  - ros-humble-ros2-controllers-test-nodes
ros2controlcli:
  ubuntu:
  - ros-humble-ros2controlcli
rqt_controller_manager:
  ubuntu:
  - ros-humble-rqt-controller-manager
rqt_joint_trajectory_controller:
  ubuntu:
  - ros-humble-rqt-joint-trajectory-controller
serial:
  ubuntu:
  - ros-humble-serial
robotiq_driver:
  ubuntu:
  - ros-humble-robotiq-driver
steering_controllers_library:
  ubuntu:
  - ros-humble-steering-controllers-library
ackermann_steering_controller:
  ubuntu:
  - ros-humble-ackermann-steering-controller
bicycle_steering_controller:
  ubuntu:
  - ros-humble-bicycle-steering-controller
transmission_interface:
  ubuntu:
  - ros-humble-transmission-interface
tricycle_controller:
  ubuntu:
  - ros-humble-tricycle-controller
tricycle_steering_controller:
  ubuntu:
  - ros-humble-tricycle-steering-controller
velocity_controllers:
  ubuntu:
  - ros-humble-velocity-controllers
