name: builder

on:
  workflow_dispatch:
  push:

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - name: ROS buildfarm
        uses: jspricke/ros-deb-builder-action@v1.0
        with:
          DEB_DISTRO: humble
          ROS_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
